version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: tyrell-sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tyrell_jobs
      MYSQL_USER: tyrellroot
      MYSQL_PASSWORD: secret
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dumps/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./dumps:/dumps

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: tyrell-elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=secret
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  app:
    image: node:14
    container_name: tyrell-app
    working_dir: /app
    volumes:
      - ./nodejs:/app
      - ./dumps:/dumps
      - ./result:/result
    depends_on:
      - mysql
      - elasticsearch 
    command: 
      - /bin/sh
      - -c
      - | 
        cd /app/ &&
        npm install &&
        sleep infinity

volumes:
  mysql-data:
  es-data:
